### ISSUE TITLE
[bug] Segmentation fault when creating two or more GroupCallFactory and join

### ISSUE THREAD

**Issue by sam01101** [MarshalX/tgcalls#111]
## Machine Environment

VM: Raspberry Pi 4B+
VM `uname -a`: `Linux ubuntu 5.4.0-1038-raspi #41-Ubuntu SMP PREEMPT Thu Jun 17 14:14:11 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`
Version: [1.0.0](https://github.com/MarshalX/tgcalls/tree/1.0.0)
Bridage: `pyrogram`

## Problem

Cause `Segmentation fault` when created 2+ `GroupCallFactory` and invoke `start`

#### Environment
- Normal chat group with voice chat `disabled`

#### Steps to reproduce
1. Start connect to group call by crate a new `GroupCallFactory` and calling `group_call.start`
- You should catch the exception and get a `RuntimeError` with `Chat without a voice chat`
2. Connect again by crate a new `GroupCallFactory` and calling `group_call.start` again (Leave old `GroupCallFactory` alone)
- Excepted: `RuntimeError` | Got: `Segmentation fault (core dumped)`

#### Solution
- Delete the other `GroupCallFactory` OR reuse old `GroupCallFactory`

**Comment by sam01101** [comment]
I've found the solution, but this still need to be fixed.

**Comment by MarshalX** [comment]
I will look into this after the vacation. Thanks for the solution found and a detailed description of the bug.

**Comment by MarshalX** [comment]
Did you mean this code for reproduce the bug?
``python
    try:
        gcf = GroupCallFactory(client)
        gc = gcf.get_file_group_call('input.raw')
        await gc.start('@ilya_marshal')
    except RuntimeError:
        print('pass1')

    try:
        gcf2 = GroupCallFactory(client)
        gc2 = gcf2.get_file_group_call('input.raw')
        await gc2.start('@ilya_marshal')
    except RuntimeError:
        print('pass2')
```

**Comment by MarshalX** [comment]
Any news? I cant reproduce it with code above (but I use dev version of lib with fixes of pointers). Iam going to close this issue

**Comment by sam01101** [comment]
Sorry, it's looks like I can't reproduce with demo code too 😂
I'll close this, sorry for disturbing for that long and late reply
