### ISSUE TITLE
[bug - GroupCallFile] File ends early before actual end when disabled `play_on_repeat`

### ISSUE THREAD

**Issue by sam01101** [MarshalX/tgcalls#112]
## Machine Environment

VM: Raspberry Pi 4B+
VM `uname -a`: `Linux ubuntu 5.4.0-1038-raspi #41-Ubuntu SMP PREEMPT Thu Jun 17 14:14:11 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`
Version: [1.0.0](https://github.com/MarshalX/tgcalls/tree/1.0.0)
Bridage: `pyrogram`

## Problem

When play almost the end of the file, it ends early.

## Reproduce

1. Create a `GroupCallFile` with `play_on_repeat=False`
2. Play a file by setting `input_filename`
3. Wait until the end, your audio should suddenly cut off and invoked `PLAYOUT_ENDED` (If handler setted)

## Guessing
- Native end the file too quickly with `play_on_repeat=False`

#### Solution
- Put `play_on_repeat=True` or just simply don't set it, when the end of song set `input_filename=""`

**Comment by MarshalX** [comment]
how much earlier?

**Comment by MarshalX** [comment]
Does the file end earlier than necessary or does the event fire before the file ends?

**Comment by sam01101** [comment]
> how much earlier?

I didn't calculate it, but I guess it's about 5-10s

> Does the file end earlier than necessary or does the event fire before the file ends?

The file end earlier than necessary, and the event fire normally

**Comment by MarshalX** [comment]
Is sound so strange

**Comment by sam01101** [comment]
I'm still testing for more cases to see how to reproduce more stable

**Comment by sam01101** [comment]
After doing a manually convert of `ffmpeg`, I've found that sometimes the audio got "cut off", A.K.A Another half didn't convert complete.
I'll keep testing is this problem always occur and update.

**Comment by sam01101** [comment]
I'm closing this, it's `ffmpeg` problem.
It happened randomly, sigh...
