### ISSUE TITLE
[Question] Stereo audio is muxed to mono when playing

### ISSUE THREAD

**Issue by sam01101** [MarshalX/tgcalls#113]
When doing a conversation of `ffmpeg -i ... -ac 2 ...` and convert back it works fine,

but when I play this raw file on voice chat, it seems muxed into mono.

After a little searching I've found that:

On <https://github.com/pytgcalls/pytgcalls>'s README, the ffmpeg command wrote `-ac 1`

A related issue with WebRTC <https://bugs.chromium.org/p/webrtc/issues/detail?id=8133>

My question is: Is that normal to have a stereo audio muxed into mono when playing?

**Comment by rojserbest** [comment]
- This lib isn't pytgcalls/pytgcalls.
- Your conversion command should be: `ffmpeg -y -i input -f s16le -ac 2 -ar 48000 output`.

**Comment by sam01101** [comment]
Moved: https://github.com/MarshalX/tgcalls/discussions/114
