### ISSUE TITLE
Add integration with ffmpeg as an optional dependency

### ISSUE THREAD

**Issue by MarshalX** [MarshalX/tgcalls#15]
Add methods for converting files, support for FIFO files for live broadcasts

FIFO: http://man7.org/linux/man-pages/man7/fifo.7.html
Tempfile for FIFO: https://stackoverflow.com/questions/1430446/create-a-temporary-fifo-named-pipe-in-python
ffmpeg for Python: https://github.com/kkroening/ffmpeg-python
Optional deps of package: https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html?highlight=extras_require#optional-dependencies

**Comment by rojserbest** [comment]
@MarshalX can’t wait...

**Comment by Sunda001** [comment]
> @MarshalX can’t wait...

same

**Comment by hdcola** [comment]
#93 This might work out just fine

**Comment by MarshalX** [comment]
This issue is deprecated and will not be implemented. If will there is auto transcoding in the library, then through ffmpeg **from the C++ side**. Not from Python
