### ISSUE TITLE
[Question] How to build tgcalls in termux android?

### ISSUE THREAD

**Issue by notudope** [MarshalX/tgcalls#157]
I try to develop my small project using this `tgcalls` library. But I found some problem when installing `pytgcalls` in Termux:

```sh
Collecting pytgcalls==2.0.0
  Using cached pytgcalls-2.0.0-py3-none-any.whl (45 kB)
ERROR: Could not find a version that satisfies the requirement tgcalls==2.0.0 (from pytgcalls) (from versions: none)
ERROR: No matching distribution found for tgcalls==2.0.0
```

I know to build this library required `docker` but termux not supported yet.

My question is how to build `pytgcalls` including `tgcalls` in **Termux Android**? If you have some small stuff like a shell script you can share it, here!

**Comment by MarshalX** [comment]
try this first https://github.com/MarshalX/tgcalls/discussions/44#discussioncomment-797659

**Comment by notudope** [comment]
> try this first [#44 (comment)](https://github.com/MarshalX/tgcalls/discussions/44#discussioncomment-797659)

ok thanks, working for me! I hope the next release also supported in Termux without proot 🤙

**Comment by notudope** [comment]
SOLVED!
