### ISSUE TITLE
segmentation fault error, using dev12

### ISSUE THREAD

**Issue by SpEcHiDe** [MarshalX/tgcalls#160]
Steps to reproduce
1) https://gist.github.com/MarshalX/3c99fcae532178928d93a7aae6f0efde
2) replace INPUT_SOURCE url using
youtube-dl -g https://youtu.be/aqz-KE-bpKQ -f "best[ext=mp4]"
3) replace INPUT_SOURCE url using
youtube-dl -g https://youtu.be/aqz-KE-bpKQ -f "243"

Actual Behaviour
the url obtained using step 3, works 

the url obtained using step 2, shows: https://nekobin.com/vofujuzusu

**Comment by MarshalX** [comment]
should be fixed in dev15 

`pip install pytgcalls==3.0.0.dev15`
