### ISSUE TITLE
Core Dumped 

### ISSUE THREAD

**Issue by Achu2234** [MarshalX/tgcalls#162]
When we steram yt lives after some min the error core dumbed coming after yt vidio or media have no problem this issue only when we steram   yt live

![image](https://user-images.githubusercontent.com/75154223/132169164-f848b3e6-164e-470e-bc30-faccfb1b5b45.png)

### Url of live : https://youtu.be/JstrU2QnMY0

**Comment by MarshalX** [comment]
Which pytgcalls version?

**Comment by Achu2234** [comment]
> Which pytgcalls version?

dev13

**Comment by Achu2234** [comment]
> Which pytgcalls version?

**Comment by MarshalX** [comment]
> > Which pytgcalls version?
> 
> 
> 
> dev13

Try start video without audio. Is the error still exists?

**Comment by Achu2234** [comment]
> > > Which pytgcalls version?
> > 
> > 
> > dev13
> 
> Try start video without audio. Is the error still exists?

ok sir

**Comment by Achu2234** [comment]
sir same error

**Comment by MarshalX** [comment]
> sir same error

Are you using pafy to get video source?

**Comment by Achu2234** [comment]
yes

**Comment by MarshalX** [comment]
> yes

try this temp solution

video = pafy.new('https://www.youtube.com/watch?v=7tNtU5XFwrU')
video_source = video.getbest().url
for stream in video.streams:
    if stream.resolution == '1280x720':
        video_source = stream.url

The main idea is pass only 720p video stream

**Comment by Achu2234** [comment]
ok sir

you mean i want to change 
  ###           video = m.text.split(None, 1)[1]
            youtube_regex = (
                                         r'(https?://)?(www\.)?'
                                       '(youtube|youtu|youtube-nocookie)\.(com|be)/'
                                       '(watch\?v=|embed/|v/|.+\?v=)?([^&=%\?]{11})')
            youtube_regex_match = re.match(youtube_regex, video)
            if youtube_regex_match:
            	try:
            		yt = pafy.new(video)
            		best = yt.getbest()
            		video_url = best.url
this to

  video = pafy.new('vidio')
video_source = video.getbest().url
for stream in video.streams:
if stream.resolution == '1280x720':
video_source = stream.url_
