### ISSUE TITLE
Dont work pip install pytgcalls==3.0.0.dev24

### ISSUE THREAD

**Issue by west9635** [MarshalX/tgcalls#202]
![image](https://github.com/MarshalX/tgcalls/assets/110269829/d889756d-9459-4843-be62-5cd026cc2e6f)
![Uploading image.jpg…]()

**Comment by MarshalX** [comment]
https://github.com/MarshalX/tgcalls/discussions/44#discussioncomment-454263

**Comment by west9635** [comment]
<img width="840" alt="telegram" src="https://github.com/MarshalX/tgcalls/assets/110269829/2005f6e0-a35e-4f52-b7df-50e922e4475a">

dont work it
