### ISSUE TITLE
.stop_playout()  sometimes leads to connection errors

### ISSUE THREAD

**Issue by MarshalX** [MarshalX/tgcalls#3]
> btw stop_playout is buggy sometimes it destroys pyrogram handler

> Happens to me too but idk if that's the reason or not.

> no idea it happens sometimes

> ![2021-03-01 01 55 51](https://user-images.githubusercontent.com/15520314/109440087-0c6f8f00-7a42-11eb-9a55-da2ba2b003ed.jpg)
> aha i catch the errors so this was caused pyrogram handler stopped working, this is when i do .stop_playout or its equivalent to .input_file = '' and this happened too to .input_file = audio_files which is when i tried to change an audio and errors occured sometimes but audio still running but it will be crashed too later

> weird it happens to .stop_playout() it means i did nothing to path

**Comment by StarkGang** [comment]
Had Same issues, the pyrogram handler got stuck, and i had to restart the whole program to fix this. this happens sometimes, not everytime.

**Comment by MarshalX** [comment]
> Had Same issues, the pyrogram handler got stuck, and i had to restart the whole program to fix this. this happens sometimes, not everytime.

By call of .stop_playout?

**Comment by MarshalX** [comment]
I believe that the latest versions do not have this problem. If necessary, we will reopen
