### ISSUE TITLE
pyrogram handlers are stopped working caused by .stop() method of group_call

### ISSUE THREAD

**Issue by Sunda001** [MarshalX/tgcalls#39]
so i wanted to record and stop the record but it seems like **.stop()** method is not working properly.

here is my code:
-> record code:
    ```group_call = pytgcalls.GroupCall(client, '', 'output.raw', False, '')```
    ```await group_call.start(chat_id, enable_action=False)```

-> stop record code: 
    ```await group_call.stop()```

this is what hapenned in my logs: 
- python logs from pytgcalls logs: https://nekobin.com/cepotuqodi 
- tgcalls logs: https://nekobin.com/lewilacica (and you said this one is fine)

after those logs existed, all of my pyrogram handlers are stopped working!

**Comment by MarshalX** [comment]
Please provide a ready-made code that I can run on myself to get the problem. logs are also not shown in full. I need everything, not a piece.

**Comment by Sunda001** [comment]
the logs are full, it is what i saw in my terminal and i just copied all of them.

**Comment by MarshalX** [comment]
Tgcalls logs isn’t full

**Comment by Sunda001** [comment]
full code: https://del.dog/lawycromut.py
full tgcalls logs: https://nekobin.com/yawivicuje
in my vps it keeps looping and ctrl+c cant stop it, i need to use ctrl+z and finding the proccess id then killing it manually, here is the screenshoot of the looping proccess: https://telegra.ph/file/82cafa2ce98aea476059c.jpg

**Comment by MarshalX** [comment]
![image](https://user-images.githubusercontent.com/15520314/110255924-47744400-7fa7-11eb-824a-21981ea828d9.png)
works fine for me...

**Comment by Sunda001** [comment]
try record and stop again after u stop it

**Comment by MarshalX** [comment]
I log in and log out 5 times without restarting. All perfectly

**Comment by Sunda001** [comment]
i dont know it sometimes work and somtimes doesnt work when i do .stop()

**Comment by Sunda001** [comment]
and when it doesnt work the logs and the code is what i have given before

**Comment by Sunda001** [comment]
it sometimes doesnt work when the first try of using .stop()

**Comment by Sunda001** [comment]
i tried it just now, for first try .start() and .stop() its working fine but for the second time of using .stop() i got the same issues just like before
![Screenshot_2021-03-08-04-58-52-048_com termux](https://user-images.githubusercontent.com/32301831/110256537-06daf180-7fcc-11eb-83e5-68f3d19326cc.jpg)
![Screenshot_2021-03-08-04-58-48-571_com termux](https://user-images.githubusercontent.com/32301831/110256540-0a6e7880-7fcc-11eb-8cb1-6c0bc78ee09d.jpg)
![Screenshot_2021-03-08-05-00-26-298_com termux](https://user-images.githubusercontent.com/32301831/110256541-0b9fa580-7fcc-11eb-8e6d-e6021f0f6a8b.jpg)

here is the full logs: https://nekobin.com/fecanogeso

**Comment by MarshalX** [comment]
Are you sure you showed all your code? Every line is important ... By the way, try the version from the dev branch. At least one bug will be fixed (with an endless request for descriptions of participants)

**Comment by Sunda001** [comment]
yeah it is exactly all of my code, okay i will update dev branch

**Comment by Sunda001** [comment]
it seems like working fine now with new updates of dev branch
