### ISSUE TITLE
freeze after .stop() sometimes

### ISSUE THREAD

**Issue by dashezup** [MarshalX/tgcalls#53]
Sometimes it fully freeze after calling `.stop()`, handlers and other plugins stops working, the only way to solve this is `kill -9` the process and start the userbot again.

### Step to reproduce:
1. start the userbot with the following smart plugin
2. send `!join`, prints "joined the VC", wait for a few seconds for joining
3. send `!leave`, prints "left the VC", or freeze and can't be closed by pressing <kbd>CTRL+c</kbd>

if it prints "left the VC" then repeat from step 2 until reproduce this. Sometimes I reproduce this after the third attempt to `!leave`, sometimes fifth, could even on the first.

Version: `pytgcalls==0.0.12`
Code (Pyrogram Smart Plugin):
```
from pyrogram import Client, filters
from pyrogram.types import Message
from pytgcalls import GroupCall

group_call = GroupCall(None)


@Client.on_message(filters.outgoing
                   & filters.regex("^!join$"))
async def join_group_call(client, m: Message):
    group_call.client = client
    await group_call.start(m.chat.id)
    print("joined the VC")


@Client.on_message(filters.outgoing
                   & filters.regex("^!leave$"))
async def leave_voice_chat(client, m: Message):
    await group_call.stop()
    print("left the VC")


@Client.on_message(filters.outgoing
                   & filters.regex("^!vc$"))
async def list_voice_chat(client, m: Message):
    print(f"VC: {group_call.full_chat.id}")
```

**Comment by MarshalX** [comment]
Pls check on 0.0.13

**Comment by dashezup** [comment]
0.0.13 does not have this issue :+1:
