### ISSUE TITLE
Unable to rejoin Group Call if stuck on read

### ISSUE THREAD

**Issue by alemidev** [MarshalX/tgcalls#70]
Joining a group call and leaving without playing audio will make tgcalls not join voice chats anymore until restarted.

## Steps to reproduce
* Make a FIFO file: `mkfifo newfile`
* Start pyrogram + tgcalls
* Join group call with, as input file, the FIFO we made before (`newfile`)
* Leave group call before writing anything on the FIFO file

After this, no group call can be joined anymore until process is restarted. Playing anything prevents this from happening.

**Comment by MarshalX** [comment]
https://stackoverflow.com/questions/5782279/why-does-a-read-only-open-of-a-named-pipe-block

**Comment by MarshalX** [comment]
https://stackoverflow.com/questions/25546619/work-with-fifo-in-c-blocking-read

**Comment by MarshalX** [comment]
> Nonblocking I/O is possible by using the fcntl(2)
       F_SETFL operation to enable the O_NONBLOCK open file status flag.
from https://man7.org/linux/man-pages/man7/pipe.7.html

fcntl - https://man7.org/linux/man-pages/man2/fcntl.2.html

**Comment by MarshalX** [comment]
U should use GroupCallRaw instead GroupCall and pass bytes directly from ffmpeg 
![AB29963A-3256-4F68-B28B-8EF4CE6E2B0F](https://user-images.githubusercontent.com/15520314/122043158-5145e880-cddb-11eb-801a-f65cfaf7cd24.png)

**Comment by rojserbest** [comment]
> You should use GroupCallRaw instead of GroupCall and pass bytes directly from ffmpeg
> ![AB29963A-3256-4F68-B28B-8EF4CE6E2B0F](https://user-images.githubusercontent.com/15520314/122043158-5145e880-cddb-11eb-801a-f65cfaf7cd24.png)

Nice
