### ISSUE TITLE
Sound playback Caton

### ISSUE THREAD

**Issue by hdcola** [MarshalX/tgcalls#93]
My environment:
macOS 11.4
Python 3.9.5
tgcalls               0.0.16
pytgcalls             0.0.23
Pyrogram              1.2.9

I transcoded the m4a file into raw by ffmp3g, and there is no problem with using audacity to listen to the sound. The following settings are used when importing audacity:

<img width="283" alt="image" src="https://user-images.githubusercontent.com/1254855/124755279-29890280-def9-11eb-921b-231fca5cb45b.png">

If I use pytgcall to play, I can clearly hear a pause of a few microseconds. I don't know what is wrong with my environment? Or is this a known issue?

**Comment by MarshalX** [comment]
What command did you use to transcode file?

**Comment by hdcola** [comment]
> What command did you use to transcode the file?

    ffmpeg.input(file_path).output(
        out,
        format='s16le',
        acodec='pcm_s16le',
        ac=2,
        ar='48k',
        loglevel='error'
    ).overwrite_output().run_async()

**Comment by MarshalX** [comment]
And how did you try to play this file?

**Comment by hdcola** [comment]
> And how did you try to play this file?

https://github.com/hdcola/chstockbot/blob/main/musicbot/services/callsmusic/callsmusic.py

Here is my service for playing music. Directly call the set_stream function inside

**Comment by MarshalX** [comment]
> > And how did you try to play this file?
> 
> https://github.com/hdcola/chstockbot/blob/main/musicbot/services/callsmusic/callsmusic.py
> 
> Here is my service for playing music. Directly call the set_stream function inside

Do you try to run example from main readme of this lib with your transcoded file? If not, you should try

**Comment by hdcola** [comment]
> > > And how did you try to play this file?
> > 
> > 
> > https://github.com/hdcola/chstockbot/blob/main/musicbot/services/callsmusic/callsmusic.py
> > Here is my service for playing music. Directly call the set_stream function inside
> 
> Do you try to run example from main readme of this lib with your transcoded file? If not, you should try

I used this sample code

https://github.com/MarshalX/tgcalls/blob/main/examples/player_as_smart_plugin.py

Still the same problem reproduced. Could it be the version of Python or some other lib?

**Comment by MarshalX** [comment]
> > > > And how did you try to play this file?
> > > 
> > > 
> > > https://github.com/hdcola/chstockbot/blob/main/musicbot/services/callsmusic/callsmusic.py
> > > Here is my service for playing music. Directly call the set_stream function inside
> > 
> > 
> > Do you try to run example from main readme of this lib with your transcoded file? If not, you should try
> 
> I used this sample code
> 
> https://github.com/MarshalX/tgcalls/blob/main/examples/player_as_smart_plugin.py
> 
> Still the same problem reproduced. Could it be the version of Python or some other lib?

It sounds so strange. Do u have the m1 mac?

**Comment by hdcola** [comment]
> It sounds so strange. Do u have the m1 mac?

My Mac is an Intel Core I5 CPU, not a new M1 CPU

**Comment by MarshalX** [comment]
> > It sounds so strange. Do u have the m1 mac?
> 
> My Mac is an Intel Core i5 CPU, not a new M1 CPU

I have no idea how to help you(

**Comment by hdcola** [comment]
Thank you very much for your reply. I will continue to observe the performance on different machines. The environment I will eventually run on will be Raspberry Pi. I don’t know what the effect will be.

**Comment by hdcola** [comment]
I have now tried two different Macs. This problem occurs with different versions of Python, maybe because of MacOS?

**Comment by MarshalX** [comment]
> I have now tried two different Macs. This problem occurs with different versions of Python, maybe because of MacOS?

What version of macos do you use?

**Comment by hdcola** [comment]
> What version of macos do you use?

all is 11.4 (macOS Big Sur)

**Comment by MarshalX** [comment]
> > What version of macos do you use?
> 
> all is 11.4 (macOS Big Sur)

me too

**Comment by hdcola** [comment]
I began to suspect that there was a problem with ffmpeg or something in my code, because after I deployed it to heroku, it still appeared intermittent.

**Comment by hdcola** [comment]
Much better after using linux and replacing a Server with a better CPU. On closer inspection, I think it's a problem of ffmpeg cpu overuse. Maybe consider a real time decoding solution.
Thanks for the previous help
