### ISSUE TITLE
Queue issue

### ISSUE THREAD

**Issue by MalinrRuwan** [MarshalX/tgcalls#95]
I cloned the repo and hosted the bot in a vps everything works perfectly except the queue function. It queues in the playlist but it doesn't jump to the next song after the first one finishes but the bot leaves the VC and after the bot leave the whole queue is gone missing but if we command /skip before the first song finishes it perfectly skips the song. Please help me to fix this ASAP.

**Comment by MarshalX** [comment]
There is no queue support.
